# Generated by scripts/build_opponent_teams.py -- do not edit by hand.
# Team: Touchline FC (pro) (wall-pro)
import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from strategy import decide


TEAM = {
    "protocolVersion": "1.0",
    "name": "Touchline FC (pro)",
    "shortName": "WLP",
    "colors": {"primary": "#7637E1", "secondary": "#ABA4B7"},
    "authors": ["My Team FC opponent generator"],
    "description": "Generated opponent: wall family, pro band. behaviour from src/opponents/engine_brain.py",
}


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/v1/health":
            self.send_json(200, {"status": "ready"})
        elif self.path == "/v1/team":
            self.send_json(200, TEAM)
        else:
            self.send_json(404, {"error": "not found"})

    def do_POST(self):
        try:
            if self.path == "/v1/matches/end":
                self.send_response(204)
                self.end_headers()
                return
            body = json.loads(self.read_body())
            if self.path == "/v1/matches/start":
                self.send_json(200, {"ready": True})
            elif self.path == "/v1/decide":
                self.send_json(200, decide(body))
            else:
                self.send_json(404, {"error": "not found"})
        except (ValueError, KeyError, TypeError) as error:
            self.send_json(400, {"error": str(error)})

    def read_body(self):
        if self.headers.get("Transfer-Encoding", "").lower() == "chunked":
            chunks, total = [], 0
            while True:
                size = int(self.rfile.readline().strip().split(b";", 1)[0], 16)
                if size == 0:
                    self.rfile.readline()
                    break
                total += size
                if total > 128 * 1024:
                    raise ValueError("request too large")
                chunks.append(self.rfile.read(size))
                self.rfile.read(2)
            return b"".join(chunks)
        length = int(self.headers.get("Content-Length", "0"))
        if length > 128 * 1024:
            raise ValueError("request too large")
        return self.rfile.read(length)

    def send_json(self, status, value):
        payload = json.dumps(value, allow_nan=False, separators=(",", ":")).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, message_format, *args):
        print(json.dumps({"level": "info", "message": message_format % args}))


ThreadingHTTPServer(("0.0.0.0", 8080), Handler).serve_forever()
