"""Generated by scripts/build_opponent_teams.py -- do not edit by hand.

Team: Overload Athletic (rookie)
Edit src/opponents/engine_brain.py and regenerate instead.
"""

from __future__ import annotations

import hashlib
import math

# -- pitch and engine constants -------------------------------------------------

PITCH_LENGTH = 60.0
PITCH_WIDTH = 40.0
GOAL_CENTER_Y = 20.0
GOAL_HALF_WIDTH = 3.0
GOAL_LOW_Y = GOAL_CENTER_Y - GOAL_HALF_WIDTH
GOAL_HIGH_Y = GOAL_CENTER_Y + GOAL_HALF_WIDTH

KICK_MIN_SPEED = 12.0
KICK_MAX_SPEED = 26.0
BALL_DECAY = 0.992
CONTROL_MAX_SPEED = 5.0
CONTROL_RADIUS = 0.9
GK_REACH = 1.65
GK_DEFENSIVE_FIFTH = 0.2 * PITCH_LENGTH
GK_HOLD_AUTO = 1.25
GK_DISTRIBUTE_BEFORE = 1.0  # beat the engine's forced 1.25 s distribution
POSSESSION_PROTECTION = 0.25
KICK_COOLDOWN = 0.3
TACKLE_CLOSE = 0.8
TACKLE_REACH = 1.15
SLAP_RANGE = 1.15
SLAP_COOLDOWN = 1.5
MAX_RUN_SPEED = 8.0
CARRY_SPEED_FACTOR = 0.8

# Metres over which "how much room is there here?" is normalised. A point right
# on top of an opponent scores 0 space, and a point SPACE_RANGE metres clear of
# the nearest opponent scores the full 1.0. Was hardcoded as a bare 12.0 inside
# two helpers.
SPACE_RANGE = 12.0

# A pass landing spot needs at least this much room to be worth making.
MIN_PASS_SPACE = 0.55

# How close a defender must be to a carrier before it is worth leaving shape
# to close him down, even when the deep-press trigger has not fired.
CLOSE_DOWN_RANGE = 6.0
# How far the single ball-watcher will travel for a ball nobody holds. Kept
# tight on purpose: a loose ball is the *default* state (the engine reports
# `possessingTeam` unset for ~87% of a match), so a generous radius here is not
# a second-ball press, it is a permanent man down chasing something irrelevant.
CONTEST_RADIUS = 12.0
# Tie-break bonus so a player who cannot act this tick is not sent first.
REACH_BONUS = 6.0

DEFAULT_TICKS_PER_DECISION = 6
EDGE = 0.5  # keep targets off the boundary

# Home shape in attack-direction fractions. Index order matches the outfield
# role order the policies assume: defender, left, right, striker.
ANCHOR_DEPTH = (0.28, 0.46, 0.46, 0.72)
ANCHOR_WIDTH = (0.50, 0.18, 0.82, 0.50)

# Feint machine rates (seconds).
FEINT_MIN = 2.5
FEINT_SPREAD = 3.5
BURST_SECONDS = 1.6
BURST_SPREAD = 2.4

FEATURES = 16
ACT_SHOOT, ACT_PASS, ACT_CARRY, ACT_CLEAR, ACT_HOLD, ACT_PRESS = range(6)
ACTION_COUNT = 6

TRAINED_PARAMS: dict = {}


def _clamp(v: float, lo: float, hi: float) -> float:
    return lo if v < lo else hi if v > hi else v


def _clamp01(v: float) -> float:
    return _clamp(v, 0.0, 1.0)


def _clamp_x(x: float) -> float:
    return _clamp(x, EDGE, PITCH_LENGTH - EDGE)


def _clamp_y(y: float) -> float:
    return _clamp(y, EDGE, PITCH_WIDTH - EDGE)


def _dist(ax: float, ay: float, bx: float, by: float) -> float:
    return math.hypot(ax - bx, ay - by)


def _lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * _clamp01(t)


class _Rng:
    """Deterministic per-decision randomness.

    The engine does not hand the team a seed, so `hash()` is unusable (it is
    salted per process). A stable digest of (salt, gameId, sequence) gives the
    same stream in every replay while still differing between games and between
    opponents.
    """

    __slots__ = ("_state",)

    def __init__(self, salt: int, game_id: str, sequence: int) -> None:
        raw = f"{salt}:{game_id}:{sequence}".encode()
        digest = hashlib.blake2b(raw, digest_size=8).digest()
        self._state = int.from_bytes(digest, "big") or 0x2545F4914F6CDD1D

    def next(self) -> float:
        # xorshift64*
        x = self._state
        x ^= (x >> 12) & 0xFFFFFFFFFFFFFFFF
        x ^= (x << 25) & 0xFFFFFFFFFFFFFFFF
        x ^= (x >> 27) & 0xFFFFFFFFFFFFFFFF
        self._state = x & 0xFFFFFFFFFFFFFFFF
        return ((x * 0x2545F4914F6CDD1D) & 0xFFFFFFFFFFFFFFFF) / 2.0**64

    def chance(self, p: float) -> bool:
        return self.next() < p

    def range(self, lo: float, hi: float) -> float:
        return lo + (hi - lo) * self.next()

    def sign(self) -> float:
        return 1.0 if self.next() < 0.5 else -1.0


class _Player:
    __slots__ = ("pid", "role", "x", "y", "can_act")

    def __init__(self, pid: str, role: str, x: float, y: float, can_act: bool) -> None:
        self.pid = pid
        self.role = role
        self.x = x
        self.y = y
        self.can_act = can_act


class _Brain:
    """One match's worth of state for one opponent team."""

    def __init__(self, params: dict, game_id: str) -> None:
        self.p = params
        self.game_id = game_id
        self.salt = int(params.get("seed_salt", 0))
        self.ticks_per_decision = int(params.get("ticks_per_decision", DEFAULT_TICKS_PER_DECISION))
        self._tick_seen: int | None = None
        self.ticks = 0
        self.sequence = -1

        self.us: list[_Player] = []
        self.them: list[_Player] = []
        self.outfield: list[_Player] = []
        self.gk: _Player | None = None
        self.bx = PITCH_LENGTH / 2.0
        self.by = PITCH_WIDTH / 2.0
        self.bvx = 0.0
        self.bvy = 0.0
        self.ball_speed = 0.0
        self.we_have = False
        self.they_have = False
        self.loose = True
        self.holder: _Player | None = None
        self.their_holder: _Player | None = None
        self.score_us = 0
        self.score_them = 0

        # Transient plans: pid -> (x, y, ttl in decisions)
        self._meet: dict[str, tuple[float, float, int]] = {}
        self._support: dict[str, tuple[float, float, int]] = {}
        self._pressers: set[str] = set()
        self._marks: dict[str, str] = {}
        self._mark_for: dict[str, _Player] = {}

        # Reaction lag: a laggy side reacts to a stale ball position.
        self._lag = (self.bx, self.by)
        self._lag_ttl = 0

        # Goalkeeper possession bookkeeping, in decisions.
        self._gk_hold = 0

        # Deception (lure families).
        self._commit = [0.5, 0.5]
        self._invite_side = 1.0
        self._invite_ttl = 0
        self._burst_side = 0.0
        self._burst_ttl = 0
        self._soft_press_ttl = 0

        # Online learning (learned families).
        self.w = [0.0] * (ACTION_COUNT * FEATURES)
        self._prev_feats: list[float] | None = None
        self._prev_action: int | None = None
        self._prev_ball_x = self.bx
        self.learns = bool(params.get("learns"))
        self.alpha = float(params.get("alpha", 0.05))
        self.gamma = float(params.get("gamma", 0.95))

    # -- observation intake -----------------------------------------------------

    def update(self, obs: dict) -> None:
        p = self.p
        self.sequence = int(obs.get("sequence", self.sequence + 1))
        tick = obs.get("simulationTick")
        if self._tick_seen is not None and tick is not None:
            delta = int(tick) - self._tick_seen
            if 1 <= delta <= 60:
                # Trust the engine's own cadence over the assumed default.
                self.ticks_per_decision = int(round(0.5 * self.ticks_per_decision + 0.5 * delta))
        if tick is not None:
            self._tick_seen = int(tick)
        self.ticks += 1

        ball = obs["ball"]
        self.bx = float(ball["position"]["x"])
        self.by = float(ball["position"]["y"])
        self.bvx = float(ball.get("velocity", {}).get("x", 0.0))
        self.bvy = float(ball.get("velocity", {}).get("y", 0.0))
        self.ball_speed = math.hypot(self.bvx, self.bvy)
        self.score_us = int(obs.get("score", {}).get("us", 0))
        self.score_them = int(obs.get("score", {}).get("them", 0))

        self.us = [
            _Player(q["id"], q.get("role", "outfield"),
                    float(q["position"]["x"]), float(q["position"]["y"]),
                    bool(q.get("canAct", True)))
            for q in obs["us"]
        ]
        self.them = [
            _Player(q["id"], q.get("role", "outfield"),
                    float(q["position"]["x"]), float(q["position"]["y"]),
                    bool(q.get("canAct", True)))
            for q in obs["them"]
        ]
        # Local ids are identical on both sides: pick the keeper by role, never
        # by id.
        self.gk = next((q for q in self.us if q.role == "goalkeeper"), None)
        outfield = [q for q in self.us if q.role != "goalkeeper"]
        outfield.sort(key=lambda q: q.pid)
        self.outfield = outfield

        team = ball.get("possessingTeam")
        held = ball.get("possessedBy")
        self.we_have = team == "us"
        self.they_have = team == "them"
        self.loose = not self.we_have and not self.they_have
        self.holder = None
        self.their_holder = None
        if self.we_have:
            for q in self.us:
                if q.pid == held:
                    self.holder = q
                    break
        elif self.they_have:
            for q in self.them:
                if q.pid == held:
                    self.their_holder = q
                    break

        if self.gk is not None and self.holder is self.gk:
            self._gk_hold += 1
        else:
            self._gk_hold = 0

        # Reaction lag.
        lag_steps = int(round(float(p.get("press_delay", 0.0)) / max(self._decision_seconds(), 0.01)))
        if lag_steps <= 0:
            self._lag = (self.bx, self.by)
        else:
            self._lag_ttl += 1
            if self._lag_ttl >= lag_steps:
                self._lag = (self.bx, self.by)
                self._lag_ttl = 0

        for table in (self._meet, self._support):
            for pid in [k for k, v in table.items() if v[2] <= 0]:
                del table[pid]
            for pid, v in list(table.items()):
                table[pid] = (v[0], v[1], v[2] - 1)

        self._update_deception()

    def _decision_seconds(self) -> float:
        return self.ticks_per_decision / 60.0

    # -- shared helpers ---------------------------------------------------------

    def _ball(self) -> tuple[float, float]:
        if self.p.get("press_delay", 0.0) > 0.0:
            return self._lag
        return self.bx, self.by

    def _noise(self) -> float:
        return float(self.p.get("noise", 0.08))

    def _rng(self) -> _Rng:
        return _Rng(self.salt, self.game_id, self.sequence)

    def _nearest_foe_dist(self, x: float, y: float,
                          outfield_only: bool = False) -> float:
        """Raw metres to the closest opponent. Large means nobody is near."""
        foes = [q for q in self.them
                if not outfield_only or q.role != "goalkeeper"]
        if not foes:
            return PITCH_LENGTH
        return min(_dist(x, y, q.x, q.y) for q in foes)

    def _space_at(self, x: float, y: float) -> float:
        """1.0 = the point is completely free, 0.0 = a foe is on top of it.

        Normalised over SPACE_RANGE metres. NOTE this is *space*, not pressure:
        it grows as the nearest opponent gets further away. The old name said
        "pressure" and documented the opposite scale, which is how the
        goalkeeper ended up passing into whoever was standing closest to him.
        Use `_nearest_foe_dist` when you want metres.
        """
        return _clamp01(self._nearest_foe_dist(x, y) / SPACE_RANGE)

    def _space_outfield_at(self, x: float, y: float) -> float:
        """`_space_at` ignoring their goalkeeper, who cannot intercept a pass."""
        return _clamp01(
            self._nearest_foe_dist(x, y, outfield_only=True) / SPACE_RANGE)

    def _simulate_kick(self, x: float, y: float, tx: float, ty: float,
                       power: float, max_steps: int = 48):
        """Where the ball ends up, and when it can first be controlled.

        Returns (x, y, steps_to_control). `steps_to_control` is None when the
        ball never slows enough to be collected inside the horizon, which is the
        common case for a hard kick and the reason passes must be aimed at
        where a receiver *will be*, not where a receiver is.
        """
        v0 = KICK_MIN_SPEED + (KICK_MAX_SPEED - KICK_MIN_SPEED) * _clamp01(power)
        d = _dist(x, y, tx, ty)
        if d < 0.05:
            return x, y, 0
        vx = v0 * (tx - x) / d
        vy = v0 * (ty - y) / d
        decay = BALL_DECAY ** self.ticks_per_decision
        dt = self._decision_seconds()
        for step in range(1, max_steps + 1):
            vx *= decay
            vy *= decay
            x += vx * dt
            y += vy * dt
            if y < 0.0:
                y = -y
                vy = -vy * 0.75
            elif y > PITCH_WIDTH:
                y = 2.0 * PITCH_WIDTH - y
                vy = -vy * 0.75
            if math.hypot(vx, vy) <= CONTROL_MAX_SPEED:
                return _clamp_x(x), _clamp_y(y), step
        return _clamp_x(x), _clamp_y(y), None

    def _lane_risk(self, ax: float, ay: float, bx: float, by: float) -> float:
        """How likely an opponent is to intercept the segment a-b."""
        total = _dist(ax, ay, bx, by)
        if total < 0.1:
            return 0.0
        risk = 0.0
        for q in self.them:
            if q.role == "goalkeeper":
                continue
            t = ((q.x - ax) * (bx - ax) + (q.y - ay) * (by - ay)) / (total * total)
            if 0.0 <= t <= 1.0:
                perp = _dist(q.x, q.y, ax + (bx - ax) * t, ay + (by - ay) * t)
                if perp < 3.0:
                    risk += (3.0 - perp) / 3.0
        return risk

    def _shot_is_on_target(self, x: float, y: float, power: float) -> bool:
        """Does a straight kick at the goal mouth actually cross the line?"""
        _, _, steps = self._simulate_kick(x, y, PITCH_LENGTH, GOAL_CENTER_Y, power)
        return steps is not None

    def _best_shot_y(self, x: float, y: float) -> float:
        """Aim away from their keeper: the far post is the whole game."""
        gks = [q for q in self.them if q.role == "goalkeeper"]
        keeper_y = gks[0].y if gks else GOAL_CENTER_Y
        if self.holder is None:
            return GOAL_CENTER_Y
        # Shoot toward whichever post the keeper is furthest from.
        if keeper_y < GOAL_CENTER_Y:
            aim = GOAL_HIGH_Y - 0.8
        elif keeper_y > GOAL_CENTER_Y:
            aim = GOAL_LOW_Y + 0.8
        else:
            aim = GOAL_CENTER_Y
        return aim

    def _collection_point(self, x: float, y: float) -> tuple[float, float, float]:
        """Where to run so we meet the current free ball as it slows."""
        steps = 14
        decay = BALL_DECAY ** self.ticks_per_decision
        dt = self._decision_seconds()
        cx, cy = x, y
        for _ in range(steps):
            cx += self.bvx * decay * dt
            cy += self.bvy * decay * dt
            decay *= BALL_DECAY ** self.ticks_per_decision
            if math.hypot(self.bvx * decay, self.bvy * decay) <= CONTROL_MAX_SPEED:
                break
        return _clamp_x(cx), _clamp_y(cy), steps * dt

    # -- planning ---------------------------------------------------------------

    def _press_plan(self, bx: float, by: float) -> set[str]:
        """Trigger-based pressing. Never 'everyone chases the ball'.

        Two jobs, and the second one used to be missing entirely:

        1. They have the ball. Press the carrier when the trigger fires, and
           also send the nearest defender to close down whenever they are close
           enough to actually reach him. A trigger that only fires deep in our
           own half left the whole team parked while they walked the ball up
           the pitch, which is what "they avoid the ball" looked like.
        2. The ball is loose. Someone must always go and win it. Previously
           this returned an empty set for a loose ball, so second balls and
           deflections were simply given away.
        """
        p = self.p
        if not self.outfield:
            self._pressers = set()
            return self._pressers
        if self._soft_press_ttl > 0:
            self._soft_press_ttl -= 1
        intensity = _clamp01(float(p.get("press_intensity", 0.6)))
        if self._soft_press_ttl > 0:
            intensity = min(intensity, 0.25)

        if self.loose:
            self._pressers = self._contest_plan(bx, by, intensity)
            return self._pressers

        if not self.they_have or self.their_holder is None:
            self._pressers = set()
            return self._pressers

        trigger_x = float(p.get("press_trigger", 0.45)) * PITCH_LENGTH
        # Press when they are in our half, when they are goal-side of our line,
        # or when the ball is already in our defensive third.
        dangerous = self.their_holder.x < trigger_x or bx < 18.0
        order = sorted(
            self.outfield, key=lambda q: (_dist(q.x, q.y, bx, by), q.pid)
        )
        if not dangerous:
            # Still not a full press, but never stand off a man who is right
            # in front of us: the closest defender closes him down.
            chaser = order[0]
            gap = _dist(chaser.x, chaser.y, self.their_holder.x,
                        self.their_holder.y)
            self._pressers = {chaser.pid} if gap <= CLOSE_DOWN_RANGE else set()
            return self._pressers

        count = 1 + int(round(intensity * 2.5))
        self._pressers = {q.pid for q in order[: max(1, min(count, len(order)))]}
        return self._pressers

    def _contest_plan(self, bx: float, by: float,
                      intensity: float) -> set[str]:
        """Who goes for a ball nobody is holding.

        The engine reports `possessingTeam` as unset for most of a match (the
        ball is only "possessed" while a player is actively controlling it), so
        this is the *default* off-ball case, not a rare second ball. It
        therefore sends exactly one man -- the nearest -- rather than a pack.
        An earlier version sent two whenever the ball was loose, which is
        correct for a genuine second ball and catastrophic here: with `loose`
        true ~87% of ticks it meant two players permanently abandoning shape,
        and the team got walked over 32-1.
        """
        if not self.outfield:
            return set()
        order = sorted(
            self.outfield,
            key=lambda q: (_dist(q.x, q.y, bx, by) - REACH_BONUS * q.can_act,
                           q.pid),
        )
        nearest = order[0]
        # Do not cross half the pitch for a ball that is not ours to win yet.
        if _dist(nearest.x, nearest.y, bx, by) > CONTEST_RADIUS:
            return set()
        return {nearest.pid}

    def _mark_plan(self) -> dict[str, str]:
        """Bind each threat to a defender, goal-side."""
        marks: dict[str, str] = {}
        self._mark_for: dict[str, _Player] = {}
        if not self.outfield:
            return marks
        threats = sorted(
            (q for q in self.them if q.role != "goalkeeper"),
            key=lambda q: q.x,
        )
        defenders = sorted(self.outfield, key=lambda q: q.pid)
        if not threats:
            return marks
        # The deepest threat gets the most defensive marker.
        for index, threat in enumerate(threats):
            if index >= len(defenders):
                break
            marks[threat.pid] = defenders[index].pid
            # Reverse lookup keyed by *our* player id, holding the threat
            # object itself. Both sides may use the same ids (`src/sim.py`
            # builds the away lineup with the home ids), so matching
            # `marks[threat.pid] == my_id` inverts to "my_id == my_id" for
            # every defender at once and sends the whole team to the same man.
            self._mark_for[defenders[index].pid] = threat
        self._marks = marks
        return marks

    def _mark_point(self, threat: _Player) -> tuple[float, float]:
        """Stand goal-side of the threat, between it and our net."""
        d = _dist(threat.x, threat.y, 0.0, GOAL_CENTER_Y)
        if d < 0.5:
            d = 0.5
        gx = threat.x * (1.0 - 3.0 / d)
        gy = threat.y + (GOAL_CENTER_Y - threat.y) * (3.0 / d)
        return _clamp_x(gx), _clamp_y(gy)

    def _shape_target(self, q: _Player, index: int) -> tuple[float, float]:
        """Base formation, shifted by the ball, with width and depth kept."""
        p = self.p
        bx, by = self._ball()
        depth = ANCHOR_DEPTH[index % len(ANCHOR_DEPTH)]
        width = ANCHOR_WIDTH[index % len(ANCHOR_WIDTH)]
        compactness = _clamp01(float(p.get("compactness", 0.6)))
        line = _clamp01(float(p.get("line_height", 0.5)))

        # The block slides with the ball but never fully follows it: the
        # defensive line is the average of a base line and the ball.
        base_line = 0.25 + 0.35 * line
        bx_frac = _clamp01(bx / PITCH_LENGTH)
        block = _lerp(base_line, bx_frac, 0.55)
        # Compactness pulls depth back toward our own goal.
        depth = depth * (1.0 - 0.35 * compactness) + block * 0.55

        tx = _clamp_x(depth * PITCH_LENGTH)
        ty = _clamp_y(width * PITCH_WIDTH)

        # Marking and support override the base shape.
        # The old guard was `self._marks.get(q.pid) == q.pid`, but `_marks` is
        # keyed by *their* player ids, so it never matched and marking silently
        # never happened. Use the reverse map, which is keyed by our own id and
        # therefore cannot collide when both sides share id strings.
        if self.they_have:
            threat = self._mark_for.get(q.pid)
            if threat is not None:
                tx, ty = self._mark_point(threat)
        meet = self._meet.get(q.pid)
        if meet is not None:
            tx, ty = meet[0], meet[1]
        if q.pid in self._support:
            sx, sy, _ = self._support[q.pid]
            tx, ty = sx, sy
        return tx, ty

    def _rest_defence_ok(self, q: _Player) -> bool:
        """Is this player already providing cover against a break?"""
        bx, by = self._ball()
        return q.x < bx - 2.0 or q.x < 20.0

    def _choose_cover_side(self) -> float:
        """Push the defensive block toward the side the ball is on."""
        return -1.0 if self.by < GOAL_CENTER_Y else 1.0

    def _non_presser_target(self, q: _Player, index: int) -> tuple[float, float]:
        """Off-ball positioning: cover, overload, or rest defence."""
        p = self.p
        bx, by = self._ball()
        family = p.get("family", "possession")
        # Rest defence: keep two players behind the ball when they have it.
        if self.they_have:
            behind = [r for r in self.outfield if r.x < bx]
            if len(behind) < 2 and q.x > bx - 1.0:
                return _clamp_x(max(4.0, bx - 9.0)), _clamp_y(GOAL_CENTER_Y + (q.y - GOAL_CENTER_Y) * 0.5)

        if family in ("overload", "wall", "tika"):
            # Attack the flank, but keep one body in the middle.
            side = self.p.get("load_side", 1.0) if family == "overload" else self._choose_cover_side()
            if index in (1, 2):
                ty = _lerp(q.y, GOAL_CENTER_Y + side * (PITCH_WIDTH * 0.42), 0.75)
                return _clamp_x(bx + 6.0), _clamp_y(ty)
        if family == "counter" and self.we_have:
            # Stay deep and spring when they commit.
            return _clamp_x(min(24.0, bx - 4.0)), _clamp_y(ANCHOR_WIDTH[index % 4] * PITCH_WIDTH)
        if family == "high_press" and not self.they_have:
            # Offside trap: hold a high line, spring on a backwards pass.
            return _clamp_x(min(34.0, bx + 12.0)), _clamp_y(ANCHOR_WIDTH[index % 4] * PITCH_WIDTH)
        return self._shape_target(q, index)

    # -- possession -------------------------------------------------------------

    def _on_ball(self, q: _Player) -> dict | None:
        p = self.p
        rng = self._rng()
        can_act = q.can_act
        goal_dist = PITCH_LENGTH - q.x
        shoot_range = float(p.get("shoot_range", 18.0))

        if can_act and goal_dist <= shoot_range:
            power = _clamp01(float(p.get("shoot_power", 0.75)) + 0.15)
            aim_y = self._best_shot_y(q.x, q.y)
            aim = {"x": PITCH_LENGTH, "y": aim_y}
            if self._shot_is_on_target(q.x, q.y, power):
                ambition = _clamp01(float(p.get("shot_ambition", 0.6)))
                if goal_dist <= 8.0 or rng.chance(0.35 + 0.65 * ambition):
                    return {"type": "shoot", "target": aim, "power": power}

        solution = self._pass_solution(q)
        if solution is not None:
            aim, power, meet, flight = solution
            for mate in self.outfield:
                if mate.pid != q.pid and _dist(mate.x, mate.y, meet[0], meet[1]) <= (
                    MAX_RUN_SPEED * flight + 1.2
                ):
                    self._meet[mate.pid] = (meet[0], meet[1], 4)
                    break
            self._support[q.pid] = (*self._support_run(q), 4)
            return {"type": "pass", "target": {"x": aim[0], "y": aim[1]}, "power": power}

        # Nothing safe: carry. A carried ball moves at 6.4 m/s and can be
        # dribbled into the shooting range; standing still never helps.
        return None

    def _support_run(self, q: _Player) -> tuple[float, float]:
        side = self._choose_cover_side()
        return (
            _clamp_x(q.x + 8.0),
            _clamp_y(GOAL_CENTER_Y + side * 9.0),
        )

    def _pass_solution(self, q: _Player):
        """Search aim x power for a pass a teammate can actually collect.

        Forward-first: a pass that retreats is only considered when nothing
        goes forward, and one that dumps the ball into our own defensive sixth
        is never considered at all. Without that ordering the search will happily
        play a 7 m retreat to the corner because the receiver happens to be
        standing there, which hands possession back for nothing.

        Scores progression, space, receiver timing, lane risk, and (for the
        deception families) a directional bias. Returns the best
        (aim, power, collection_point, flight_seconds) or None.
        """
        p = self.p
        base_power = _clamp01(float(p.get("pass_power", 0.45)))
        # A kick's target only sets the *direction*; the ball keeps rolling until
        # it slows. Without an explicit travel budget a soft pass aimed 22 m
        # ahead can carry 50 m, so "build-up" quietly becomes a long ball into
        # the opponent's penalty area. Vertical families are allowed a longer
        # budget on purpose.
        max_travel = float(p.get("max_pass_travel", 32.0))
        best = None
        best_score = -1e9
        best_rank = -1
        for power in (max(0.18, base_power - 0.18), base_power, min(0.95, base_power + 0.22)):
            for step in range(12):
                ang = step * (2.0 * math.pi / 12.0) + 0.31
                ax = _clamp_x(q.x + math.cos(ang) * 22.0)
                ay = _clamp_y(q.y + math.sin(ang) * 22.0)
                if _dist(q.x, q.y, ax, ay) < 5.0:
                    continue
                if abs(ay - q.y) < 3.0 and ax <= q.x - 1.0:
                    continue  # sideways or backwards: not a real forward option
                cx, cy, steps = self._simulate_kick(q.x, q.y, ax, ay, power)
                if steps is None:
                    continue
                flight = steps * self._decision_seconds()
                if abs(cy - GOAL_CENTER_Y) < 1.0 and cx > 55.0:
                    continue  # that is a shot, not a pass
                # Never play the ball into our own defensive sixth while we are
                # still building: that is a punt, and a punt is a `clear`.
                if cx < 10.0 and q.x < 16.0:
                    continue
                travel = _dist(q.x, q.y, cx, cy)
                if travel > max_travel:
                    continue
                # Forward-first ranking. A retreat is only acceptable when the
                # ball is already deep in our own half, where resetting play can
                # be the right answer, and never by more than a few metres.
                delta = cx - q.x
                if delta < -2.0:
                    continue
                if delta < 0.0:
                    rank = 0 if q.x > 32.0 else 1
                elif delta < 8.0:
                    rank = 2
                else:
                    rank = 3
                mate = None
                need = 1e9
                for m in self.outfield:
                    if m.pid == q.pid:
                        continue
                    d = _dist(m.x, m.y, cx, cy)
                    if d < need:
                        need, mate = d, m
                if mate is None or need > MAX_RUN_SPEED * flight + 2.5:
                    continue
                if mate in self._pressers:
                    continue  # a presser cannot also be the receiver
                if self._space_outfield_at(cx, cy) < 0.30:
                    continue
                progress = delta / PITCH_LENGTH * 2.0
                clearance = self._space_outfield_at(cx, cy)
                lane = self._lane_risk(q.x, q.y, cx, cy)
                score = (
                    2.0 * progress
                    + 0.8 * min(clearance, 1.0)
                    - 0.5 * min(need, 30.0) / 10.0
                    - 0.03 * travel
                    - 0.02 * abs(cy - GOAL_CENTER_Y)  # keep play off the paint
                    + 0.6 * (1.0 - clearance)
                    - 0.5 * float(p.get("risk", 0.5)) * lane
                    + self._pass_bias(cx, cy)
                )
                # Rank dominates: a much better-scored sideways ball is still
                # worse than a mediocre forward one.
                if rank > best_rank or (rank == best_rank and score > best_score):
                    best_rank = rank
                    best_score = score
                    best = ((ax, ay), power, (cx, cy), flight)
        return best

    def _pass_bias(self, cx: float, cy: float) -> float:
        p = self.p
        if p.get("family") != "lure":
            return 0.0
        if self._burst_ttl > 0 and self._burst_side != 0.0:
            return 1.2 * self._burst_side * (1.0 if cy >= GOAL_CENTER_Y else -1.0)
        if self.we_have and self.bx < 21.0:
            return -0.8 if cx > self.bx else 0.0
        return 0.0

    def _carry_target(self, q: _Player) -> tuple[float, float]:
        """Dribble toward goal, bending away from the nearest defender."""
        p = self.p
        shoot_range = float(p.get("shoot_range", 18.0))
        goal_dist = PITCH_LENGTH - q.x
        goal_y = GOAL_CENTER_Y
        if self.them:
            blocker = min(self.them, key=lambda o: _dist(q.x, q.y, o.x, o.y))
            if _dist(q.x, q.y, blocker.x, blocker.y) < 6.0:
                away = -1.0 if q.y < blocker.y else 1.0
                goal_y = _clamp_y(GOAL_CENTER_Y + away * (4.0 + 6.0 * float(p.get("risk", 0.5))))
        if goal_dist <= shoot_range * 0.8:
            # Do not dribble onto the goal line: a carried ball stays glued to
            # the carrier and cannot score, so this parks the ball on the line.
            return _clamp_x(q.x), _lerp(q.y, GOAL_CENTER_Y, 0.2)
        lead = 0.10 + 0.10 * float(p.get("directness", 0.5))
        return _clamp_x(q.x + lead * PITCH_LENGTH), _lerp(q.y, goal_y, 0.35)

    # -- deception --------------------------------------------------------------

    def _update_deception(self) -> None:
        p = self.p
        if p.get("family") != "lure":
            return
        bx, by = self._ball()
        low = high = 0
        for q in self.them:
            if q.role == "goalkeeper":
                continue
            if _dist(q.x, q.y, bx, by) <= 8.0:
                if q.y < GOAL_CENTER_Y:
                    low += 1
                else:
                    high += 1
        alpha = 0.25
        self._commit[0] = (1.0 - alpha) * self._commit[0] + alpha * low
        self._commit[1] = (1.0 - alpha) * self._commit[1] + alpha * high
        self._invite_ttl -= 1
        self._burst_ttl = max(0, self._burst_ttl - 1)
        self._soft_press_ttl = max(0, self._soft_press_ttl - 1)

        if self.we_have and self._burst_ttl <= 0:
            self._burst_side = self._weak_channel()
            if self._burst_side != 0.0:
                self._burst_ttl = int(round((BURST_SECONDS + BURST_SPREAD * float(p.get("deception", 0.8))) / self._decision_seconds()))
        elif not self.we_have and self._invite_ttl <= 0:
            self._invite_side = self._weak_channel() or 1.0
            if self._rng().chance(0.5 * float(p.get("deception", 0.8))):
                self._soft_press_ttl = int(round(1.2 / self._decision_seconds()))
            self._invite_ttl = int(
                round((FEINT_MIN + FEINT_SPREAD * self._rng().next()) / self._decision_seconds())
            )

    def _weak_channel(self) -> float:
        lo, hi = self._commit
        if abs(lo - hi) < 0.15:
            return 0.0
        read = -1.0 if lo < hi else 1.0
        # Deliberately fallible: a lure that is always right is a fixed habit
        # the opponent can learn, which defeats the point of deceiving anyone.
        if self._rng().chance(self._noise() * 1.5):
            return -read
        return read

    # -- online learning --------------------------------------------------------

    def _features(self) -> list[float]:
        p = self.p
        goal_dist = _clamp01((PITCH_LENGTH - self.bx) / PITCH_LENGTH)
        control = 1.0 if self.we_have else 0.0
        poss = 1.0 if self.they_have else 0.0
        # `space` is 1.0 when nobody is near the ball, so `press` is its inverse
        # and really does mean "how crowded is it".
        space = self._space_outfield_at(self.bx, self.by)
        press = 1.0 - space
        free = space
        support = (
            min(_dist(q.x, q.y, self.bx, self.by) for q in self.outfield) / 30.0
            if self.outfield else 1.0
        )
        clock = _clamp01(self.ticks / 1800.0)
        return [
            1.0, control, poss, 1.0 - goal_dist, free, press, min(support, 1.0), goal_dist,
            control * (1.0 - goal_dist), control * free, poss * press,
            control * float(p.get("directness", 0.5)), poss * float(p.get("compactness", 0.6)),
            clock, clock * control, self._noise(),
        ]

    def _q(self, action: int, feats: list[float]) -> float:
        base = action * FEATURES
        w = self.w
        total = 0.0
        for i, f in enumerate(feats):
            total += w[base + i] * f
        return total

    def _learn_update(self, feats: list[float], action: int, reward: float) -> None:
        if self._prev_feats is None or self._prev_action is None:
            self._prev_feats, self._prev_action = feats, action
            return
        base = self._prev_action * FEATURES
        current = self._q(self._prev_action, self._prev_feats)
        step = self.alpha * (reward + self.gamma * self._q(action, feats) - current)
        for i, f in enumerate(self._prev_feats):
            if f:
                self.w[base + i] += step * f
        self._prev_feats, self._prev_action = feats, action

    def _learn_reward(self) -> float:
        p = self.p
        progress = (self.bx - self._prev_ball_x) / PITCH_LENGTH * 6.0
        control = 1.0 if self.we_have else 0.0
        r = 0.6 * progress + 0.3 * (control - 0.5)
        r += 0.3 * (self.score_us - self.score_them)
        self._prev_ball_x = self.bx
        return r

    def _learned_action(self, q: _Player) -> int:
        goal_dist = PITCH_LENGTH - q.x
        shoot_range = float(self.p.get("shoot_range", 18.0))
        mask = [False] * ACTION_COUNT
        mask[ACT_CARRY] = True
        mask[ACT_HOLD] = True
        mask[ACT_CLEAR] = bool(not self.they_have and self._pressers)
        if q.can_act:
            if goal_dist <= shoot_range:
                mask[ACT_SHOOT] = self._shot_is_on_target(
                    q.x, q.y, _clamp01(float(self.p.get("shoot_power", 0.75)) + 0.15)
                )
            mask[ACT_PASS] = self._pass_solution(q) is not None
        mask[ACT_PRESS] = not self.we_have
        feats = self._features()
        best, best_q = ACT_HOLD, -1e18
        rng = self._rng()
        for a in range(ACTION_COUNT):
            if not mask[a]:
                continue
            qv = self._q(a, feats)
            if rng.chance(self._noise()):
                qv = rng.next()
            if qv > best_q:
                best, best_q = a, qv
        self._learn_update(feats, best, self._learn_reward())
        return best

    # -- goalkeeper -------------------------------------------------------------

    def _gk_plan(self) -> dict:
        p = self.p
        gk = self.gk
        if gk is None:
            return {"target": {"x": 3.0, "y": GOAL_CENTER_Y}, "speed": 0.5, "action": {"type": "none"}}
        bx, by = self._ball()
        aggression = float(p.get("gk_aggression", 0.4))

        # Holding the ball: distribute before the engine's forced 1.25 s kick.
        if self.holder is gk:
            hold = self._gk_hold * self._decision_seconds()
            if gk.can_act and hold >= GK_DISTRIBUTE_BEFORE * 0.4:
                # Score every reachable target by how much room the ball would
                # land in and pick the roomiest. The old code took the first
                # candidate whose "pressure" was above a threshold, but that
                # value is *space* -- so it rejected the safe, open targets and
                # played the ball to whichever attacker was standing nearest
                # the landing spot. Ranking by space fixes that directly.
                best = None
                best_key = None
                for mate in self.outfield:
                    if _dist(gk.x, gk.y, mate.x, mate.y) < 4.0:
                        continue
                    cx, cy, steps = self._simulate_kick(
                        gk.x, gk.y, mate.x, mate.y, 0.34, max_steps=64
                    )
                    if steps is None:
                        continue
                    room = self._space_outfield_at(cx, cy)
                    # Prefer room, then a short hop, then a progressive target.
                    key = (round(room, 3), -_dist(gk.x, gk.y, mate.x, mate.y),
                           mate.x)
                    if best_key is None or key > best_key:
                        best_key = key
                        best = (mate, (cx, cy), room)
                if best is not None:
                    mate, _, room = best
                    if room >= MIN_PASS_SPACE:
                        return {
                            "target": {"x": mate.x, "y": mate.y},
                            "speed": 0.6,
                            "action": {"type": "pass", "target": {"x": mate.x, "y": mate.y}, "power": 0.34},
                        }
                    # Every option is crowded, but the roomiest is still far
                    # better than a hoof: take the best available and let the
                    # receiver shield it.
                    if room >= MIN_PASS_SPACE * 0.6:
                        return {
                            "target": {"x": mate.x, "y": mate.y},
                            "speed": 0.6,
                            "action": {"type": "pass", "target": {"x": mate.x, "y": mate.y}, "power": 0.34},
                        }
                # Nowhere safe: hoof it long, into space away from their keeper
                # and away from the nearest man, not blindly down the middle.
                # Try both flanks and keep the one our opponents are furthest from.
                best_hoof = None
                for side in (self._choose_cover_side(), -self._choose_cover_side()):
                    ty = _clamp_y(GOAL_CENTER_Y + side * 9.0)
                    room = self._space_at(_clamp_x(bx + 26.0), ty)
                    if best_hoof is None or room > best_hoof[0]:
                        best_hoof = (room, _clamp_x(bx + 26.0), ty)
                target = {"x": best_hoof[1], "y": best_hoof[2]}
                return {
                    "target": {"x": target["x"], "y": target["y"]},
                    "speed": 0.6,
                    "action": {"type": "clear", "target": target, "power": 0.85},
                }
            # Just received it: hold position, let the hold timer run.
            return {
                "target": {"x": _clamp_x(bx * 0.25), "y": _clamp_y(bx * 0.25 + by * 0.75)},
                "speed": 0.35,
                "action": {"type": "none"},
            }

        # Positioning: stay inside the defensive fifth, on the ball-goal line,
        # pushed off the line for a coming cross or a sweeper ball.
        depth = 2.6 + 4.0 * aggression
        sweep = 0.0
        if self.loose and self.ball_speed <= CONTROL_MAX_SPEED:
            # Come out for a dying ball in our own area, but only if no
            # outfielder is closer to it than we are. `_space_outfield_at` > 0.6
            # means the nearest outfield opponent is more than 7.2 m away.
            if (self.bx < GK_DEFENSIVE_FIFTH
                    and self._space_outfield_at(self.bx, self.by) > 0.6):
                sweep = 1.0
        tx = _clamp(bx * (0.22 + 0.16 * aggression) + depth * sweep, 1.0, GK_DEFENSIVE_FIFTH - 1.0)
        ty = _clamp_y(_lerp(by, GOAL_CENTER_Y, 0.62))
        if self.loose and self.ball_speed <= CONTROL_MAX_SPEED and self.bx < GK_DEFENSIVE_FIFTH:
            tx = _clamp_x(self.bx)
            ty = _clamp_y(self.by)
        action = {"type": "none"}
        if self.their_holder is not None and gk.can_act:
            if _dist(gk.x, gk.y, self.their_holder.x, self.their_holder.y) < TACKLE_REACH:
                action = {"type": "tackle"}
        return {"target": {"x": tx, "y": ty}, "speed": 0.7 + 0.25 * float(p.get("gk_speed", 0.6)), "action": action}

    # -- main entry point -------------------------------------------------------

    def _outfield_action(self, q: _Player, index: int) -> dict:
        """Plan for one outfielder.

        Always returns the same shape -- ``{target, speed, action}`` -- so the
        caller never has to guess whether it got a movement plan or a bare
        action. The carrier's movement is decided by the caller, which knows
        whether a kick was requested.
        """
        p = self.p
        rng = self._rng()
        noise = self._noise()
        tempo_speed = _clamp01(0.75 + 0.25 * float(p.get("tempo", 0.8)))

        def plan(tx: float, ty: float, speed: float, action: dict) -> dict:
            return {
                "target": {"x": _clamp_x(tx), "y": _clamp_y(ty)},
                "speed": _clamp01(speed),
                "action": action,
            }

        if self.holder is q:
            if not q.can_act:
                return plan(q.x, q.y, 0.0, {"type": "none"})
            action: dict | None = None
            if self.learns:
                chosen = self._learned_action(q)
                if chosen == ACT_SHOOT:
                    power = _clamp01(float(p.get("shoot_power", 0.75)) + 0.15)
                    action = {"type": "shoot", "target": {"x": PITCH_LENGTH, "y": self._best_shot_y(q.x, q.y)}, "power": power}
                elif chosen == ACT_PASS:
                    solution = self._pass_solution(q)
                    if solution is not None:
                        aim, power, meet, flight = solution
                        for mate in self.outfield:
                            if mate.pid != q.pid and _dist(mate.x, mate.y, meet[0], meet[1]) <= (
                                MAX_RUN_SPEED * flight + 1.2
                            ):
                                self._meet[mate.pid] = (meet[0], meet[1], 4)
                                break
                        action = {"type": "pass", "target": {"x": aim[0], "y": aim[1]}, "power": power}
                elif chosen == ACT_CLEAR:
                    action = {
                        "type": "clear",
                        "target": {"x": PITCH_LENGTH, "y": _clamp_y(GOAL_CENTER_Y + self._choose_cover_side() * 10.0)},
                        "power": 0.8,
                    }
                elif chosen == ACT_HOLD:
                    action = {"type": "none"}
            if action is None and not self.learns:
                action = self._on_ball(q)
            return plan(q.x, q.y, 0.3, action or {"type": "none"})

        if self.their_holder is not None and q.pid in self._pressers:
            holder = self.their_holder
            action = {"type": "none"}
            if q.can_act:
                d = _dist(q.x, q.y, holder.x, holder.y)
                if d < TACKLE_REACH:
                    action = {"type": "tackle"}
                elif d < 2.6 and float(p.get("tackling", 0.5)) > 0.5 and rng.chance(0.5):
                    action = {"type": "slap"}
            if q.x < 8.0 and holder.x < 12.0:
                # Refuse to follow them into our own box: hold the covering line.
                return plan(holder.x - 1.5, holder.y, 0.9, action)
            return plan(holder.x, holder.y, 1.0, action)

        # A loose ball is a chance to win possession. The designated contesters
        # go and meet it where it will actually slow to something collectable.
        # The old guard required the nearest opponent to be more than 6 m away,
        # so the ball was chased only when nobody was interested -- which is
        # precisely how you hand second balls to the other team.
        if self.loose and q.pid in self._pressers:
            cx, cy, _flight = self._collection_point(self.bx, self.by)
            return plan(cx, cy, 1.0, {"type": "none"})

        tx, ty = self._non_presser_target(q, index)
        # Execution error. A noiseless opponent is a different opponent.
        spread = noise * 5.0
        tx += rng.range(-spread, spread)
        ty += rng.range(-spread, spread)
        speed = tempo_speed
        if self.they_have and not self._rest_defence_ok(q):
            speed = min(1.0, speed + 0.2)
        return plan(tx, ty, speed, {"type": "none"})

    def decide(self, obs: dict) -> dict:
        self.update(obs)
        bx, by = self._ball()
        self._press_plan(bx, by)
        self._mark_plan() if (self.we_have or self.they_have) else None
        if not (self.we_have or self.they_have):
            self._marks = {}

        intents = []
        for q in self.us:
            if q.role == "goalkeeper":
                plan = self._gk_plan()
                intents.append({
                    "playerId": q.pid,
                    "move": {"target": plan["target"], "speed": _clamp01(plan["speed"])},
                    "face": {"x": PITCH_LENGTH, "y": GOAL_CENTER_Y},
                    "action": plan["action"],
                })
                continue

            index = next((i for i, m in enumerate(self.outfield) if m.pid == q.pid), 0)
            # Exactly one plan per player: `_outfield_action` searches kicks and
            # updates the learned weights, so calling it twice would double both
            # the cost and the learning signal.
            plan = self._outfield_action(q, index)
            action = plan["action"]
            if self.holder is q:
                if action["type"] == "none":
                    # No kick available: walk the ball into shooting range.
                    tx, ty = self._carry_target(q)
                    speed = 0.75 + 0.25 * float(self.p.get("tempo", 0.8))
                else:
                    tx, ty = q.x, q.y
                    speed = 0.3
                intents.append({
                    "playerId": q.pid,
                    "move": {"target": {"x": _clamp_x(tx), "y": _clamp_y(ty)}, "speed": _clamp01(speed)},
                    "face": {"x": PITCH_LENGTH, "y": GOAL_CENTER_Y},
                    "action": action,
                })
                continue
            intents.append({
                "playerId": q.pid,
                "move": {"target": plan["target"], "speed": _clamp01(plan["speed"])},
                "face": {"x": bx, "y": by},
                "action": action,
            })

        return {
            "protocolVersion": obs.get("protocolVersion", "1.0"),
            "gameId": obs["gameId"],
            "sequence": obs["sequence"],
            "intents": intents,
        }


_BRAINS: dict[str, _Brain] = {}
_MAX_CACHED_BRAINS = 4


def decide(observation) -> dict:
    """Entry point. Per-match state is keyed by `gameId` and never shared."""
    game_id = observation["gameId"]
    brain = _BRAINS.get(game_id)
    if brain is None:
        if len(_BRAINS) >= _MAX_CACHED_BRAINS:
            _BRAINS.clear()
        brain = _Brain(TRAINED_PARAMS, game_id)
        _BRAINS[game_id] = brain
    return brain.decide(observation)

# --- Overload Athletic (rookie): generated parameters -------------------------------------
PARAMS = {   'compactness': 0.45,
    'directness': 0.6,
    'family': 'overload',
    'gk_aggression': 0.3,
    'gk_speed': 0.55,
    'noise': 0.22,
    'press_delay': 0.3,
    'press_intensity': 0.5,
    'risk': 0.5,
    'seed_salt': 3635028631,
    'shoot_range': 12.0,
    'tempo': 0.7,
    'width': 0.9}
TRAINED_PARAMS = PARAMS
